--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NhanAZ/Calculator
build-by-default: true
branches:
- arithmexp
projects:
  Calculator:
    path: ""
    libs:
      - src: muqsit/arithmexp/arithmexp
        version: 0.1.22
      - src: NhanAZ/libBedrock/libBedrock
        version: 0.0.1
...
