---
name: Calculator
version: 0.0.11
main: NhanAZ\Calculator\Main
api: 4.0.0

website: https://github.com/NhanAZ
description: Execute math expressions in the server or console on PocketMine-MP servers.
author: NhanAZ

commands:
  calculator:
    description: "Perform a math operation"
    usage: "/calculator <expression>"
    permission: calculator.command
    aliases: ["calc"]
permissions:
  calculator.command:
    default: true
    description: "Allows the use of /calculator"
...
